export const ADDBTN_OPEN = "ADDBTN_OPEN";
export const ADDBTN_CLOSE = "ADDBTN_CLOSE";

export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_OPEN = "MODAL_OPEN";

export const TASK_DELETED = "TASK_DELETED";
export const TASK_NOTD = "TASK_NOTD";

export const TASK_CHECKED = "TASK_CHECKED";
export const TASK_UNCHECKED = "TASK_UNCHECKED";

export const EVENT_MODAL_OPEN = "EVENT_MODAL_OPEN";
export const EVENT_MODAL_CLOSE = "EVENT_MODAL_CLOSE";

export const SUBTASK_STATUS_TRUE = "SUBTASK_STATUS_TRUE";
export const SUBTASK_STATUS_FALSE = "SUBTASK_STATUS_FALSE";

export const FILE_DELETED = "FILE_DELETED";
export const FILE_NOT_DELETED = "FILE_NOT_DELETED";

export const FILE_MODAL_OPEN = "FILE_MODAL_OPEN";
export const FILE_MODAL_CLOSE = "FILE_MODAL_CLOSE";

export const HABIT_MODAL_OPEN = "HABIT_MODAL_OPEN";
export const HABIT_MODAL_CLOSE = "HABIT_MODAL_CLOSE";
